version: "3.8"

services:
  mongo:
    image: mongo:7-jammy
    container_name: cms_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cms_assignment
    volumes:
      - mongo_data:/data/db
    networks:
      - cms_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cms_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/cms_assignment
      JWT_SECRET: enterprise_cms_production_super_secret_jwt_key_2026
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:5173
      PUBLIC_URL: http://localhost:3000
      UPLOAD_DIR: uploads
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - cms_network

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    container_name: cms_admin_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - cms_network

  public-frontend:
    build:
      context: ./public-frontend
      dockerfile: Dockerfile
    container_name: cms_public_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - cms_network

volumes:
  mongo_data:

networks:
  cms_network:
    driver: bridge
